config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"

  namespace :game_masters do
    resources :universes do
      resources :adventures, module: "universes", only: [:new, :create, :edit, :update, :destroy]
    end
  end

  namespace :players do
    resources :universes, only: [:index]
  end
end

app/models/adventure.rb
class Adventure < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :universe

  scope :recent, -> { order(created_at: :desc).limit(3) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/universe.rb
class Universe < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true

  belongs_to :game_master, class_name: "User"
  has_many   :adventures

  scope :recent, -> { order(created_at: :desc) }

  def recent_adventures
    adventures.recent
  end
end

app/models/user.rb
class User < ApplicationRecord
  GAME_MASTER = "game_master".freeze
  PLAYER      = "player".freeze

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :universes, foreign_key: :game_master_id

  def game_master?
    role == GAME_MASTER
  end

  def player?
    role == PLAYER
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_masters/universes/adventures_controller.rb
module GameMasters
  module Universes
    class AdventuresController < GameMastersController
      def new
        @universe = current_universe
        @adventure = Adventure.new(universe: current_universe)
      end

      def create
        @adventure = Adventure.create!(universe: current_universe,
                                       name: adventure_params[:name],
                                       description: adventure_params[:description])
        flash[:notice] = "You created an adventure: #{@adventure.name}!"
        redirect_to game_masters_universe_path(current_universe)
      end

      def edit
        @universe = current_universe
        @adventure = current_universe.adventures.find(params[:id])
      end

      def update
        current_adventure.update!(adventure_params)
        flash[:notice] = "You updated: #{current_adventure.name} adventure!"
        redirect_to game_masters_universe_path(current_universe)
      end

      def destroy
        current_adventure.destroy!
        flash[:alert] = "You removed #{current_adventure.name} adventure!"
        redirect_to game_masters_universe_path(current_universe)
      end

      private

      def adventure_params
        params.require(:adventure).permit(:name, :description)
      end

      def current_adventure
        @current_adventure ||= current_universe.adventures.find(params[:id])
      end

      def current_universe
        @current_universe ||= current_game_master.universes.find(params[:universe_id])
      end
    end
  end
end

app/controllers/game_masters/universes_controller.rb
module GameMasters
  class UniversesController < GameMastersController
    def index
      @universes = current_game_master.universes
    end

    def show
      @universe = current_universe
      @recent_adventures = current_universe.recent_adventures
    end

    def new
      @universe = Universe.new(game_master: current_game_master)
    end

    def create
      @universe = Universe.new(game_master: current_game_master,
                               name: universe_params[:name],
                               description: universe_params[:description])
      @universe.save!
      flash[:notice] = "You created a #{@universe.name} universe!"
      redirect_to game_masters_universes_path
    end

    def edit
      @universe = current_universe
    end

    def update
      current_universe.update!(universe_params)
      flash[:notice] = "You updated the #{current_universe.name} universe!"
      redirect_to game_masters_universes_path
    end

    def destroy
      current_universe.destroy!
      flash[:notice] = "You deleted the #{current_universe.name} universe!"
      redirect_to game_masters_universes_path
    end

    private

    def current_universe
      @current_universe ||= current_game_master.universes.find(params[:id])
    end

    def universe_params
      params.require(:universe).permit(:name, :description)
    end
  end
end

app/controllers/game_masters_controller.rb
class GameMastersController < UsersController
  before_action :authorise_game_master!

  def current_game_master
    current_user
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/players/universes_controller.rb
module Players
  class UniversesController < UsersController
    def index
      @universes = Universe.recent
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def authorise_game_master!
    return if current_user.game_master?
    flash[:alert] = "Not a Game Master"
    redirect_to :root
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_email(current_user)
    current_user&.email
  end

  def current_user_game_master?(current_user)
    current_user.game_master?
  end
end

app/views/game_masters/universes/_card.html.erb
<a href=<%= game_masters_universe_path(universe) %>>
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <p class="title is-4"><%= universe.name.truncate(23) %></p>
        </div>
        <div class="media-content">
        </div>
      </div>

      <div class="content">
        <p>
          <%= universe.description.truncate(128) %>
        </p>
        <time datetime=<%= universe.created_at.to_s(:db) %>><%= universe.created_at.to_s(:long_ordinal) %></time>

        <%= render partial: "actions", locals: { universe: universe } %>
      </div>
    </div>
  </div>
</a>

app/views/game_masters/universes/_form.html.erb
<%= form_for universe, url: url do |f| %>
  <div class="field">
    <label class="label">Name</label>
    <div class="control">
      <%= f.text_field :name, class: "input", placeholder: "Name your universe" %>
    </div>
  </div>
  <div class="field">
    <label class="label">Description</label>
    <div class="control">
      <%= f.text_area :description, class: "textarea", placeholder: "Give other players some context..." %>
    </div>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Create this Universe", class: "button is-link" %>
    </div>
  </div>
  </p>
<% end %>

app/views/game_masters/universes/adventures/_actions.html.erb
<div class="field is-grouped">
  <%= link_to('Edit', edit_game_masters_universe_adventure_path(universe_id: universe.id, id: adventure.id), class: "button is-small is-light") %>
  <%= link_to('Remove', game_masters_universe_adventure_path(universe_id: universe.id, id: adventure.id), method: :delete, class: "button is-small is-danger is-light") %>
</div>

app/views/game_masters/universes/adventures/_card.html.erb
<a href=<%= "#" %>>
  <div class="card">
    <div class="card-header">
      <p class="card-header-title">
        <%= adventure.name.truncate(23) %>
      </p>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
        </div>
        <div class="media-content">
        </div>
      </div>

      <div class="content">
        <p>
          <%= adventure.description.truncate(128) %>
        </p>

        <%= render partial: "game_masters/universes/adventures/actions", locals: { universe: universe, adventure: adventure } %>
      </div>
    </div>
  </div>
</a>

app/views/game_masters/universes/adventures/_form.html.erb
<%= form_for adventure, url: url do |f| %>
  <div class="field">
    <label class="label">Name</label>
    <div class="control">
      <%= f.text_field :name, class: "input", placeholder: "Name your adventure" %>
    </div>
  </div>
  <div class="field">
    <label class="label">Description</label>
    <div class="control">
      <%= f.text_area :description, class: "textarea", placeholder: "Give other players some context..." %>
    </div>
  </div>
  <div class="field is-grouped">
    <div class="control">
      <%= f.submit "Create this Adventure", class: "button is-link" %>
    </div>
  </div>
  </p>
<% end %>

app/views/game_masters/universes/adventures/edit.html.erb
<%= render partial: "form", locals: { adventure: @adventure, url: game_masters_universe_adventure_path(universe_id: @universe.id, id: @adventure.id) } %>

app/views/game_masters/universes/adventures/new.html.erb
<%= render partial: "form", locals: { adventure: @adventure, url: game_masters_universe_adventures_path(@universe) } %>

app/views/game_masters/universes/edit.html.erb
<%= render partial: "form", locals: { universe: @universe, url: game_masters_universe_path(@universe) } %>

app/views/game_masters/universes/index.html.erb
<section class="section">
  <div class="level">
    <div class="level-left">
      <h1 class="title">Universes</h1>
    </div>
    <div class="level-right">
      <%= link_to('Add a new Universe!', new_game_masters_universe_path, class: "button is-large") %>
    </div>
  </div>
  <div class="columns is-mobile is-multiline">
    <% @universes.each do |universe| %>
      <div class="column is-one-third">
        <%= render partial: "card", locals: { universe: universe } %>
      </div>
    <% end %>
  </div>
</section>

app/views/game_masters/universes/new.html.erb
<%= render partial: "form", locals: { universe: @universe, url: game_masters_universes_path } %>

app/views/game_masters/universes/show.html.erb
<section class="hero is-light">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @universe.name %>
      </h1>
    </div>
  </div>
</section>
<div class="container">
  <section class="section">
    <div class="columns is-mobile is-multiline">
      <div class="column is-half">
        <div class="level">
          <div class="level-left">
            <h1 class="is-size-4">Description</h1>
          </div>
        </div>
        <div class="content">
          <%= @universe.description %>
        </div>
      </div>
      <div class="column is-half">
        <div class="level">
          <div class="level-left">
            <h1 class="is-size-4">Adventures</h1>
          </div>
          <div class="level-right">
            <%= link_to('Add a new Adventure!', new_game_masters_universe_adventure_path(@universe), class: "button") %>
          </div>
        </div>
        <% @recent_adventures.each do |adventure| %>
          <div class="content">
            <%= render partial: "game_masters/universes/adventures/card", locals: { universe: @universe, adventure: adventure } %>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RpgEngine</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user_game_master?(current_user) %>
      <%= render partial: "shared/game_master_navbar", locals: { user: current_user } %>
    <% else %>
      <%= render partial: "shared/navbar", locals: { user: current_user } %>
    <% end %>

    <% if flash[:notice] %>
      <div class="notification is-primary is-light">
        <button class="delete"></button>
        <%= notice %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger is-light">
        <button class="delete"></button>
        <%= alert %>
      </div>
    <% end %>

    <main class="bd-main">
      <%= yield %>
    </main>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/players/universes/_card.html.erb
<a href=<%= game_masters_universe_path(universe) %>>
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <img src="https://bulma.io/images/placeholders/1280x960.png" alt="Placeholder image">
      </figure>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <p class="title is-4"><%= universe.name.truncate(23) %></p>
        </div>
        <div class="media-content">
        </div>
      </div>

      <div class="content">
        <p>
          <%= universe.description.truncate(128) %>
        </p>
        <time datetime=<%= universe.created_at.to_s(:db) %>><%= universe.created_at.to_s(:long_ordinal) %></time>
      </div>
    </div>
  </div>
</a>

app/views/players/universes/index.html.erb
<section class="section">
  <div class="level">
    <div class="level-left">
      <h1 class="title">Available Universes</h1>
    </div>
  </div>
  <div class="columns is-mobile is-multiline is-centered">
    <% @universes.each do |universe| %>
      <div class="column is-one-third">
        <%= render partial: "card", locals: { universe: universe } %>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p>
      <strong>RPG-Engine</strong> by <a href="https://github.com/TomaszKorbecki">Tomasz Korbecki</a> and <a href="https://github.com/bigbob33">Michał Kosyk</a>. The source code is licensed
      <a href="http://opensource.org/licenses/mit-license.php">MIT</a>.
    </p>
  </div>
</footer>

app/views/shared/_game_master_navbar.html.erb
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <div class="navbar-item">
      <h1 class="title">RPG-Engine</h1>
    </div>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to('Home', root_path, class: "navbar-item") %>
      </div>
      <div class="navbar-item">
        <%= link_to('Universes', game_masters_universes_path, class: "navbar-item") %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "button") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: "button") %>
        <%  end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <h1>RPG-Engine</h1>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <div class="navbar-item">
        <%= link_to('Home', root_path, class: "navbar-item") %>
      </div>
      <div class="navbar-item">
        <%= link_to('Universes', players_universes_path, class: "navbar-item") %>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "button") %>
        <% else %>
          <%= link_to('Login', new_user_session_path, class: "button") %>
        <%  end %>
      </div>
    </div>
  </div>
</nav>